os: osx
osx_image: xcode11

branches:
  only:
  - master

language: node_js
node_js:
  - '10'

cache:
  directories:
    - ./node_modules


name: "Deploy web production"
install:
  - cd web && npm install
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - npm run deploy-prod
        
